name: Deploy Nuxt to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build static site
      run: npm run construction

    - name: Create deployment archive
      run: |
        cd .output/public
        tar -czf ../../site.tar.gz .

    - name: Prepare deployment directory
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 57-102620.ssh.hosting-ik.com
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        timeout: 30s
        command_timeout: 10s
        script: |
          mkdir -p sites/upload-biennale.ch
          cd sites/upload-biennale.ch
          rm -rf * 2>/dev/null || true
          echo "Directory prepared"

    - name: Transfer files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 57-102620.ssh.hosting-ik.com
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: "site.tar.gz"
        target: "sites/upload-biennale.ch/"
        timeout: 60s

    - name: Extract files
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 57-102620.ssh.hosting-ik.com
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        timeout: 30s
        command_timeout: 10s
        script: |
          cd sites/upload-biennale.ch
          tar -xzf site.tar.gz
          rm site.tar.gz
          echo "Deployment completed"
          ls -la | head -10