name: Deploy Nuxt to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build static site
      run: npm run construction

    - name: Install sshpass and rsync
      run: sudo apt-get update && sudo apt-get install -y sshpass rsync

    - name: Deploy with rsync
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "Starting deployment..."
        rsync -avz --delete --stats --timeout=30 \
          -e "sshpass -e ssh -o StrictHostKeyChecking=no -o ConnectTimeout=15 -o ServerAliveInterval=10" \
          .output/public/ \
          ${{ secrets.SSH_USERNAME }}@57-102620.ssh.hosting-ik.com:~/sites/upload-biennale.ch/
        echo "Deployment completed successfully!"