name: Deploy Nuxt to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Install sshpass and rsync
      run: sudo apt-get update && sudo apt-get install -y sshpass rsync

    - name: Deploy with rsync
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "Starting deployment..."
        rsync -avz --delete --stats --timeout=30 \
          --exclude='.git*' \
          --exclude='.DS_Store' \
          --exclude='node_modules' \
          --exclude='*.log' \
          -e "sshpass -e ssh -o StrictHostKeyChecking=no -o ConnectTimeout=15 -o ServerAliveInterval=10" \
          ./ \
          ${{ secrets.SSH_USERNAME }}@57-102988.ssh.hosting-ik.com:/srv/customer/sites/dev.upload-biennale.ch/
        echo "Deployment completed successfully!"

    - name: Install dependencies on server
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "Installing dependencies on server..."
        sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@57-102988.ssh.hosting-ik.com \
          "cd /srv/customer/sites/dev.upload-biennale.ch/ && npm ci --production"
        echo "Dependencies installed successfully!"

    - name: Test deployment
      run: |
        echo "Files deployed successfully. To start manually:"
        echo "1. SSH into server: ssh ${{ secrets.SSH_USERNAME }}@57-102988.ssh.hosting-ik.com"
        echo "2. cd /srv/customer/sites/dev.upload-biennale.ch/"
        echo "3. node .output/server/index.mjs"